### ISSUE TITLE
Upstream values for requests timeout and wait duration

### ISSUE THREAD

**Issue by pdpinch** [mitodl/xqueue-watcher#6]
Submit PR #2 upstream to edX

**Comment by gsidebo** [comment]
Currently open: https://github.com/edx/xqueue-watcher/pull/29

**Comment by pdpinch** [comment]
This was merged upstream in https://github.com/edx/xqueue-watcher/commit/7762bc3022d1e2507d0e77f4a41a1e3fd62eadc9
